"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { LogOut, RefreshCw, ShieldCheck } from "lucide-react";
import { useZerionMarketStream } from "@/hooks/use-zerion-market-stream";
import { readTradingContext, writeTradingContext } from "@/lib/dashboard/trading-context";
import type { MarketInstrument } from "@/types/market";

type Account={currency:string;startingBalance:number;cashBalance:number;equity:number;buyingPower:number;dailyPnl:number;totalPnl:number};
type Position={id:string;symbol:string;market:string;quantity:number;averagePrice:number;markPrice:number;unrealizedPnl:number;realizedPnl:number;stopLoss?:number;targetPrice?:number};
type Order={id:string;symbol:string;market:string;side:string;type:string;quantity:number;status:string;createdAt:string;averageFillPrice?:number};
type Closure={id?:string;symbol:string;market:string;quantity:number;average_price?:number;averagePrice?:number;exit_price?:number;exitPrice?:number;realized_pnl?:number;realizedPnl?:number;closed_at?:string;closedAt?:string};

export function PaperSectionWorkspace({mode}:{mode:"overview"|"order"|"positions"|"pnl"|"history"|"account"}){
 const params=useSearchParams();
 const[account,setAccount]=useState<Account|null>(null),[positions,setPositions]=useState<Position[]>([]),[orders,setOrders]=useState<Order[]>([]),[closures,setClosures]=useState<Closure[]>([]),[ids,setIds]=useState<Record<string,string>>({});
 const[query,setQuery]=useState(""),[results,setResults]=useState<MarketInstrument[]>([]),[selected,setSelected]=useState<MarketInstrument|null>(null),[side,setSide]=useState("buy"),[type,setType]=useState("market"),[qty,setQty]=useState("1"),[limit,setLimit]=useState(""),[trigger,setTrigger]=useState(""),[sl,setSl]=useState(""),[target,setTarget]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[capital,setCapital]=useState("100000");
 const load=useCallback(async()=>{const rs=await Promise.all(["account","positions","orders","closures"].map(x=>fetch(`/api/paper/${x}`,{cache:"no-store"}).then(r=>r.json()).catch(()=>({data:x==="account"?null:[]}))));setAccount(rs[0].data??null);setPositions(rs[1].data??[]);setOrders(rs[2].data??[]);setClosures(rs[3].data??[])},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(account)setCapital(String(account.startingBalance))},[account]);
 useEffect(()=>{if(mode!=="order")return;const prefillInstrument=params.get("instrument")??"",prefillSymbol=params.get("symbol")??"",prefillQty=params.get("qty")??"",prefillSl=params.get("sl")??"",prefillTarget=params.get("target")??"",prefillSide=(params.get("side")??"").toLowerCase();if(prefillQty)setQty(prefillQty);if(prefillSl)setSl(prefillSl);if(prefillTarget)setTarget(prefillTarget);if(prefillSide==="buy"||prefillSide==="sell")setSide(prefillSide);if(!prefillInstrument&&!prefillSymbol)return;const q=prefillSymbol||prefillInstrument.replace(/^upstox:/i,"").replace(/^coindcx:/i,"");setQuery(q);void fetch(`/api/markets/search?q=${encodeURIComponent(q)}`,{cache:"no-store"}).then(r=>r.json()).then(b=>{const rows=(b.data??[]) as MarketInstrument[],hit=rows.find(x=>x.id===prefillInstrument)??rows.find(x=>x.symbol.toUpperCase()===prefillSymbol.toUpperCase());if(hit){setSelected(hit);setQuery(hit.symbol)}}).catch(()=>{})},[mode,params]);
 useEffect(()=>{if(mode!=="order"||params.get("instrument")||params.get("symbol"))return;const saved=readTradingContext("paper");if(!saved?.instrumentId&&!saved?.symbol)return;const q=saved.symbol||saved.instrumentId||"";if(saved.quantity)setQty(saved.quantity);if(saved.stopLoss)setSl(saved.stopLoss);if(saved.targetPrice)setTarget(saved.targetPrice);if(saved.side==="buy"||saved.side==="sell")setSide(saved.side);setQuery(q);void fetch(`/api/markets/search?q=${encodeURIComponent(q)}`,{cache:"no-store"}).then(r=>r.json()).then(b=>{const rows=(b.data??[]) as MarketInstrument[],hit=rows.find(x=>x.id===saved.instrumentId)??rows.find(x=>x.symbol.toUpperCase()===String(saved.symbol??"").toUpperCase());if(hit){setSelected(hit);setQuery(hit.symbol)}}).catch(()=>{})},[mode,params]);
 useEffect(()=>{if(mode!=="order")return;writeTradingContext("paper",{instrumentId:selected?.id,symbol:selected?.symbol??query,market:selected?.market,provider:selected?.exchange,side:side as "buy"|"sell",orderType:type,quantity:qty,limitPrice:limit,triggerPrice:trigger,stopLoss:sl,targetPrice:target})},[limit,mode,qty,query,selected,side,sl,target,trigger,type]);
 useEffect(()=>{positions.forEach(p=>{if(ids[p.id])return;void fetch(`/api/markets/search?q=${encodeURIComponent(p.symbol)}&market=${encodeURIComponent(p.market)}`,{cache:"no-store"}).then(r=>r.json()).then(b=>{const hit=(b.data??[] as MarketInstrument[]).find((x:MarketInstrument)=>x.id.startsWith("upstox:")||x.id.startsWith("coindcx:"));if(hit)setIds(cur=>({...cur,[p.id]:hit.id}))}).catch(()=>{})})},[ids,positions]);
 const streamKeys=useMemo(()=>[...positions.flatMap(p=>[ids[p.id]??"",p.symbol]),...(selected?[selected.id,selected.symbol]:[])].filter(Boolean),[ids,positions,selected]);const live=useZerionMarketStream(streamKeys);
 const marked=useMemo(()=>positions.map(p=>{const q=live[(ids[p.id]??"").toUpperCase()]??live[p.symbol.toUpperCase()];if(!q)return p;return{...p,markPrice:q.price,unrealizedPnl:(q.price-p.averagePrice)*p.quantity}}),[ids,live,positions]);
 const open=marked.filter(p=>p.quantity!==0),unrealized=marked.reduce((s,p)=>s+p.unrealizedPnl,0),realized=closures.reduce((s,c)=>s+Number(c.realized_pnl??c.realizedPnl??0),0);
 useEffect(()=>{const v=query.trim();if(mode!=="order"||v.length<2){setResults([]);return}const c=new AbortController(),t=setTimeout(()=>void fetch(`/api/markets/search?q=${encodeURIComponent(v)}`,{cache:"no-store",signal:c.signal}).then(r=>r.json()).then(b=>setResults(b.data??[])).catch(()=>{}),180);return()=>{c.abort();clearTimeout(t)}},[mode,query]);
 async function place(){if(!selected)return;setBusy(true);try{const r=await fetch("/api/paper/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({symbol:selected.symbol,instrumentId:selected.id,market:selected.market,side,type,quantity:Number(qty),limitPrice:limit?Number(limit):undefined,stopPrice:trigger?Number(trigger):undefined,stopLoss:sl?Number(sl):undefined,targetPrice:target?Number(target):undefined})});const b=await r.json();setMessage(r.ok?`Paper order ${b.data?.order?.status??"accepted"}`:b.error?.message??"Rejected");if(r.ok)await load()}finally{setBusy(false)}}
 async function close(p:Position){if(!confirm(`Square off ${p.symbol}?`))return;await fetch("/api/paper/positions/close",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({positionId:p.id})});await load()}
 async function saveCapital(reset=false){const amount=Number(capital);if(!Number.isFinite(amount))return;if(reset&&!confirm("Reset paper account? This permanently deletes paper orders, positions and trade history."))return;setBusy(true);try{const r=await fetch("/api/paper/account",{method:reset?"DELETE":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({startingBalance:amount})});const b=await r.json();setMessage(r.ok?(reset?"Paper account reset.":"Paper capital updated."):b.error?.message??"Update failed");if(r.ok)await load()}finally{setBusy(false)}}

 const heading=(title:string,desc:string)=><div className="page-heading"><div><p className="eyebrow">PAPER TRADING</p><h1>{title}</h1><p>{desc}</p></div><span className="status-pill">No real money</span></div>;
 if(mode==="overview")return <main className="dashboard-page">{heading("Paper Overview","Provider-priced practice account overview.")}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Starting",account?.startingBalance],["Cash",account?.cashBalance],["Unrealized",unrealized],["Realized",realized]].map(([l,v])=><div className="panel" key={String(l)}><span>{l}</span><strong className="mt-2 block text-xl">{account?.currency} {Number(v??0).toLocaleString()}</strong></div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-3"><Link className="panel" href="/dashboard/paper/order">Place paper order</Link><Link className="panel" href="/dashboard/paper/positions">Open positions ({open.length})</Link><Link className="panel" href="/dashboard/paper/account">Paper capital</Link></div></main>;
 if(mode==="order")return <main className="dashboard-page">{heading("Paper Order","Real provider quote required before a paper fill.")}<section className="panel max-w-3xl space-y-4"><label>Instrument<input value={query} onChange={e=>{setQuery(e.target.value);setSelected(null)}} placeholder="TATA, TCS, NIFTY, BTC, ETH…"/></label>{results.length&&!selected?<div className="max-h-56 overflow-auto rounded-xl border border-[#E6D8C3]">{results.slice(0,30).map(x=><button key={x.id} onClick={()=>{setSelected(x);setQuery(x.symbol);setResults([])}} className="block w-full border-b border-[#E6D8C3] px-3 py-2 text-left">{x.symbol} · {x.exchange} · {x.market}</button>)}</div>:null}<div className="grid gap-3 sm:grid-cols-3"><label>Side<select value={side} onChange={e=>setSide(e.target.value)}><option value="buy">Buy</option><option value="sell">Sell</option></select></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="market">Market</option><option value="limit">Limit</option><option value="stop">Stop</option><option value="stop-limit">Stop limit</option></select></label><label>Quantity<input type="number" step="any" min="0.0001" value={qty} onChange={e=>setQty(e.target.value)}/></label></div>{(type==="limit"||type==="stop-limit")?<label>Limit price<input type="number" value={limit} onChange={e=>setLimit(e.target.value)}/></label>:null}{(type==="stop"||type==="stop-limit")?<label>Trigger price<input type="number" value={trigger} onChange={e=>setTrigger(e.target.value)}/></label>:null}<div className="grid gap-3 sm:grid-cols-2"><label>Stop loss<input type="number" value={sl} onChange={e=>setSl(e.target.value)}/></label><label>Target<input type="number" value={target} onChange={e=>setTarget(e.target.value)}/></label></div><button disabled={busy||!selected} className="zx-primary-action" onClick={()=>void place()}>{busy?"Checking provider…":"Place paper order"}</button>{message?<p>{message}</p>:null}<p className="flex gap-2 text-xs text-[#2F2A25]"><ShieldCheck className="h-4 w-4"/>No provider quote = no paper fill.</p></section></main>;
 if(mode==="positions")return <main className="dashboard-page">{heading("Paper Positions","Live marks and unrealized P&L from the shared realtime stream.")}<section className="panel overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr><th>Symbol</th><th>Qty</th><th>Average</th><th>Mark</th><th>SL</th><th>Target</th><th>P&L</th><th>Actions</th></tr></thead><tbody>{open.map(p=><tr className="border-t border-[#E6D8C3]" key={p.id}><td className="py-3">{p.symbol}</td><td>{p.quantity}</td><td>{p.averagePrice.toLocaleString()}</td><td>{p.markPrice.toLocaleString()}</td><td>{p.stopLoss?.toLocaleString()??"—"}</td><td>{p.targetPrice?.toLocaleString()??"—"}</td><td className={p.unrealizedPnl>=0?"positive":"negative"}>{p.unrealizedPnl.toLocaleString()}</td><td className="flex gap-2 py-2"><Link className="zx-secondary-action" href={`/dashboard/charts?instrument=${encodeURIComponent(ids[p.id]??"")}&symbol=${encodeURIComponent(p.symbol)}&tf=5m`}>Chart</Link><button className="zx-exit-action" onClick={()=>void close(p)}><LogOut className="mr-1 h-4 w-4"/>Exit</button></td></tr>)}</tbody></table>{!open.length?<p className="py-6">No open paper positions.</p>:null}</section></main>;
 if(mode==="pnl")return <main className="dashboard-page">{heading("Paper P&L","Realtime unrealized plus persisted realized paper results.")}<div className="mb-4 flex flex-wrap gap-2"><Link className="zx-primary-action" href="/dashboard/paper/order">New paper trade</Link><Link className="zx-secondary-action" href="/dashboard/charts">Open chart terminal</Link></div><div className="grid gap-4 sm:grid-cols-3"><div className="panel"><span>Unrealized</span><strong className={`block text-2xl ${unrealized>=0?"positive":"negative"}`}>{unrealized.toLocaleString()}</strong></div><div className="panel"><span>Realized</span><strong className={`block text-2xl ${realized>=0?"positive":"negative"}`}>{realized.toLocaleString()}</strong></div><div className="panel"><span>Daily account P&L</span><strong className={`block text-2xl ${(account?.dailyPnl??0)>=0?"positive":"negative"}`}>{account?.dailyPnl.toLocaleString()}</strong></div></div></main>;
 if(mode==="history")return <main className="dashboard-page">{heading("Paper History","Paper orders and completed paper trades.")}<section className="panel"><h2 className="text-lg font-semibold">Orders</h2>{orders.map(o=><div key={o.id} className="flex flex-wrap justify-between gap-2 border-b border-[#E6D8C3] py-3"><span>{o.symbol} · {o.side} · {o.type} · {o.quantity}</span><span>{o.status} · {new Date(o.createdAt).toLocaleString()}</span></div>)}</section><section className="panel mt-4"><h2 className="text-lg font-semibold">Closed trades</h2>{closures.map((c,i)=><div key={c.id??i} className="flex flex-wrap justify-between gap-2 border-b border-[#E6D8C3] py-3"><Link href={`/dashboard/charts?symbol=${encodeURIComponent(c.symbol)}&tf=5m`}>{c.symbol} · Open chart</Link><span>{Number(c.realized_pnl??c.realizedPnl??0).toLocaleString()}</span></div>)}</section></main>;
 return <main className="dashboard-page">{heading("Paper Account / Balance","Set practical paper capital or reset the paper account.")}<section className="panel max-w-2xl space-y-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[10000,50000,100000,500000].map(v=><button key={v} className="luxury-filter" onClick={()=>setCapital(String(v))}>₹{v.toLocaleString("en-IN")}</button>)}</div><label>Custom capital<input type="number" min="1000" value={capital} onChange={e=>setCapital(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button disabled={busy} className="zx-primary-action" onClick={()=>void saveCapital(false)}>Edit balance</button><button disabled={busy} className="zx-exit-action" onClick={()=>void saveCapital(true)}>Reset paper account</button></div>{message?<p>{message}</p>:null}<p className="text-xs text-[#2F2A25]">Changing capital requires no open positions. Reset is destructive and asks for confirmation.</p></section></main>;
}
