"use client";
import { useEffect,useMemo,useState } from "react";
export type ZerionFeedStatus="LIVE"|"RECONNECTING"|"STALE"|"DISCONNECTED";
export type ZerionLiveQuote={provider:"upstox"|"coindcx"|"forex";symbol:string;providerSymbol:string;instrumentId:string;timestamp:string;price:number;change:number;changePercent:number;previousClose:number;open:number;high:number;low:number;volume?:number;bid?:number;ask?:number;delayed?:boolean};
type GatewayEnvelope={type?:string;data?:unknown};type Listener=()=>void;
const norm=(v:string)=>v.trim().toUpperCase();
function aliases(q:ZerionLiveQuote){return [norm(q.instrumentId),norm(q.symbol),norm(q.providerSymbol),norm(q.symbol).replaceAll("/",""),norm(q.symbol).replaceAll("-","")];}
function delay(attempt:number){const base=Math.min(20000,750*2**Math.min(5,attempt));return Math.round(base*(.8+Math.random()*.4));}
class Gateway{
 socket:WebSocket|null=null;refs=new Map<string,number>();quotes=new Map<string,ZerionLiveQuote>();listeners=new Set<Listener>();reconnectTimer:ReturnType<typeof setTimeout>|null=null;healthTimer:ReturnType<typeof setInterval>|null=null;reconnectAttempt=0;status:ZerionFeedStatus="DISCONNECTED";lastQuoteAt=0;lastGatewayMessageAt=0;
 private url(){return process.env.NEXT_PUBLIC_ZERION_REALTIME_URL??"wss://zerionx1.onrender.com/realtime"}
 private emit(){for(const l of this.listeners)l()}
 private setStatus(v:ZerionFeedStatus){if(v===this.status)return;this.status=v;this.emit()}
 private health(){if(this.healthTimer)return;this.healthTimer=setInterval(()=>{if(this.socket?.readyState!==WebSocket.OPEN)return;const silence=this.lastGatewayMessageAt?Date.now()-this.lastGatewayMessageAt:0;if(silence>120000){this.setStatus("STALE");return;}if(this.status!=="LIVE")this.setStatus("LIVE")},5000)}
 private ingest(value:unknown){if(!value||typeof value!=="object")return null;const q=value as ZerionLiveQuote;if(!["upstox","coindcx","forex"].includes(q.provider)||!q.instrumentId||!q.symbol||!Number.isFinite(q.price))return null;for(const a of aliases(q))this.quotes.set(a,q);this.lastQuoteAt=Date.now();this.setStatus("LIVE");this.emit();return q}
 connect(){if(typeof window==="undefined")return;if(this.socket?.readyState===WebSocket.OPEN||this.socket?.readyState===WebSocket.CONNECTING)return;this.setStatus("RECONNECTING");const socket=new WebSocket(this.url());this.socket=socket;socket.addEventListener("open",()=>{this.reconnectAttempt=0;this.lastGatewayMessageAt=Date.now();this.setStatus("LIVE");this.health();const instruments=[...this.refs.keys()];if(instruments.length)socket.send(JSON.stringify({type:"subscribe",instruments}))});socket.addEventListener("message",e=>{this.lastGatewayMessageAt=Date.now();try{const frame=JSON.parse(e.data) as GatewayEnvelope;if(frame.type==="snapshot"&&Array.isArray(frame.data)){for(const item of frame.data)this.ingest(item);this.setStatus("LIVE");return;}if(frame.type==="quote"){this.ingest(frame.data);return;}this.setStatus("LIVE")}catch{}});socket.addEventListener("error",()=>{if(socket.readyState===WebSocket.OPEN)socket.close()});socket.addEventListener("close",()=>{if(this.socket===socket)this.socket=null;if(!this.refs.size){this.setStatus("DISCONNECTED");return;}this.setStatus("RECONNECTING");const d=delay(this.reconnectAttempt++);if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(()=>this.connect(),d)})}
 subscribe(instruments:string[],listener:Listener){this.listeners.add(listener);const wanted=[...new Set(instruments.map(norm).filter(Boolean))],added:string[]=[];for(const id of wanted){const count=this.refs.get(id)??0;this.refs.set(id,count+1);if(count===0)added.push(id)}this.connect();if(added.length&&this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify({type:"subscribe",instruments:added}));return()=>{this.listeners.delete(listener);const removed:string[]=[];for(const id of wanted){const count=this.refs.get(id)??0;if(count<=1){this.refs.delete(id);removed.push(id)}else this.refs.set(id,count-1)}if(removed.length&&this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify({type:"unsubscribe",instruments:removed}));if(!this.refs.size){if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.reconnectTimer=null;this.socket?.close();this.socket=null;this.setStatus("DISCONNECTED")}}}
 quoteFor(xs:string[]){for(const x of xs.map(norm)){const q=this.quotes.get(x);if(q)return q}return null}
 snapshot(w:Set<string>){const out:Record<string,ZerionLiveQuote>={};for(const id of w){const q=this.quotes.get(id);if(q)out[id]=q}return{quotes:out}}
}
const gateway=new Gateway();
export function subscribeZerionRealtime(instruments:string[],listener:(quote:ZerionLiveQuote|null)=>void){const notify=()=>listener(gateway.quoteFor(instruments));const off=gateway.subscribe(instruments,notify);notify();return off}
export function useZerionMarketStream(instruments:string[]){const key=instruments.map(norm).filter(Boolean).sort().join("|");const wanted=useMemo(()=>new Set(key?key.split("|"):[]),[key]);const[,render]=useState(0);useEffect(()=>{if(!wanted.size)return;return gateway.subscribe([...wanted],()=>render(v=>v+1))},[wanted]);return gateway.snapshot(wanted).quotes}
export function useZerionFeedStatus(){const[,render]=useState(0);useEffect(()=>{const l=()=>render(v=>v+1);gateway.listeners.add(l);return()=>{gateway.listeners.delete(l)}},[]);return{status:gateway.status,lastQuoteAt:gateway.lastQuoteAt,lastGatewayMessageAt:gateway.lastGatewayMessageAt,transportOpen:gateway.socket?.readyState===WebSocket.OPEN}}
