import { NextRequest } from "next/server";
import { getCoinDcxFuturesActiveInstruments,getCoinDcxMarketDetails } from "@/lib/brokers/coindcx-core";
import { getConnectedMt5Credentials } from "@/lib/brokers/connection-store";
import { mt5BridgeClient } from "@/lib/brokers/mt5-bridge-client";
import { upstoxClient } from "@/lib/brokers/upstox-client";
import { searchMarketCatalog } from "@/lib/market/market-catalog";
import { ok } from "@/lib/security/api-response";
import type { MarketInstrument,MarketKind } from "@/types/market";
type U={name?:string;short_name?:string;trading_symbol?:string;instrument_key?:string;exchange?:string;segment?:string;instrument_type?:string;lot_size?:number;tick_size?:number;expiry?:string;strike_price?:number};
function kind(r:U):MarketKind{const s=String(r.segment??"").toUpperCase(),t=String(r.instrument_type??"").toUpperCase();if(s.includes("INDEX"))return"indian-index";if(s.includes("FO")&&(t==="CE"||t==="PE"))return"indian-options";if(s.includes("FO")||t==="FUT")return"indian-futures";if(s.includes("MCX"))return"commodity";return"indian-equity"}
function mapU(r:U):MarketInstrument|null{const id=String(r.instrument_key??""),symbol=String(r.trading_symbol??r.short_name??r.name??"");if(!id||!symbol)return null;return{id:`upstox:${id}`,symbol,displayName:String(r.short_name??r.name??symbol),market:kind(r),exchange:String(r.exchange??"NSE"),currency:"INR",tickSize:Number(r.tick_size??.05),lotSize:Number(r.lot_size??1),enabled:true,providerRequired:true,searchableText:[r.name,r.short_name,r.trading_symbol,r.expiry,r.strike_price,r.instrument_type].filter(Boolean).join(" ")}}
function uniq(a:MarketInstrument[]){const s=new Set<string>();return a.filter(x=>{const k=`${x.id}|${x.symbol}`.toUpperCase();if(s.has(k))return false;s.add(k);return true})}
function aliases(q:string){const x=q.trim().toUpperCase();if(["NIFTY","NIFTY50","NIFTY 50"].includes(x))return["NIFTY","NIFTY 50"];if(["BANKNIFTY","BANK NIFTY","NIFTY BANK"].includes(x))return["BANKNIFTY","NIFTY BANK"];if(["SENSEX","BSE SENSEX"].includes(x))return["SENSEX"];return[q]}
async function india(q:string,m?:MarketKind){let f="page_number=1&records=100";if(m==="indian-equity")f+="&exchanges=NSE,BSE&segments=EQ";if(m==="indian-index")f+="&exchanges=NSE,BSE&segments=INDEX";if(m==="indian-futures")f+="&exchanges=NSE,BSE&segments=FO&instrument_types=FUT";if(m==="indian-options")f+="&exchanges=NSE,BSE&segments=FO&instrument_types=CE,PE";try{const groups=await Promise.all(aliases(q).map(async x=>{try{const r=await upstoxClient.instrumentSearch(x,f) as{data?:U[]};return(r.data??[]).map(mapU).filter((v):v is MarketInstrument=>Boolean(v))}catch{return[]}}));return uniq(groups.flat())}catch{return[]}}
async function crypto(q:string){const n=q.toUpperCase().replace(/[^A-Z0-9]/g,""),out:MarketInstrument[]=[];try{for(const r of await getCoinDcxMarketDetails()){const p=String(r.pair??""),c=String(r.coindcx_name??""),b=String(r.base_currency_short_name??""),t=String(r.target_currency_short_name??""),s=b&&t?`${b}/${t}`:c.replace("_","/");if(!`${p}${c}${b}${t}${s}`.toUpperCase().replace(/[^A-Z0-9]/g,"").includes(n))continue;out.push({id:`coindcx:${p||c}`,symbol:s,displayName:`${s} · Spot`,market:"crypto",exchange:"COINDCX",currency:t||"USDT",tickSize:1e-8,lotSize:1e-8,enabled:true,providerRequired:true})}}catch{}try{for(const p of await getCoinDcxFuturesActiveInstruments()){if(!p.toUpperCase().replace(/[^A-Z0-9]/g,"").includes(n))continue;const s=p.replace(/^B-/i,"").replace("_","/");out.push({id:`coindcx-futures:${p}`,symbol:s,displayName:`${s} · Perpetual`,market:"crypto",exchange:"COINDCX-FUTURES",currency:"USDT",tickSize:1e-8,lotSize:1e-6,enabled:true,providerRequired:true})}}catch{}return uniq(out).slice(0,100)}
async function forex(q:string){try{const c=await getConnectedMt5Credentials(),b=await mt5BridgeClient.marketSymbols(c,q) as{symbols?:Record<string,unknown>[]};return(b.symbols??[]).map(r=>({id:`forex:${String(r.name??"")}`,symbol:String(r.name??""),displayName:String(r.description??r.name??""),market:"forex" as const,exchange:"MT5",currency:String(r.currency_profit??""),tickSize:Number(r.point??1e-5),lotSize:Number(r.volume_min??.01),enabled:true,providerRequired:true,searchableText:[r.name,r.description,r.path].filter(Boolean).join(" ")})).filter(x=>x.symbol).slice(0,100)}catch{return[]}}
export async function GET(request:NextRequest){const q=request.nextUrl.searchParams.get("q")??"",m=request.nextUrl.searchParams.get("market") as MarketKind|null,local=searchMarketCatalog(q,m??undefined);if(!q.trim())return ok(local.slice(0,100));const[i,c,f]=await Promise.all([m&&!m.startsWith("indian-")&&m!=="commodity"?[]:india(q,m??undefined),m&&m!=="crypto"?[]:crypto(q),m&&m!=="forex"?[]:forex(q)]);return ok(uniq([...i,...c,...f,...local]).slice(0,120))}
