import type { Entitlements, Plan } from "@/types/entitlements";
export type PlanDefinition={id:Plan;name:string;tagline:string;monthlyPriceInr:number|null;launchPriceInr?:number|null;featured?:boolean;enterprise?:boolean;highlights:string[];simpleExamples:string[];entitlements:Entitlements};
export const planDefinitions:PlanDefinition[]=[
{id:"free",name:"Free",tagline:"Start with Indian markets.",monthlyPriceInr:0,highlights:["Indian market access","Upstox account connection","30 automation actions/month","3 AI requests/day, up to 30/month","Paper trading","Basic strategy templates"],simpleExamples:["Explain a market setup","Use a ready strategy in paper mode","Connect Upstox and explore Zerion"],entitlements:{plan:"free",markets:["india"],paperAccounts:1,strategyLimit:2,backtestRunsPerMonth:5,aiCreditsPerMonth:30,automationActionsPerMonth:30,liveExecutionsPerMonth:3,priority:"standard",concurrentStrategies:1}},
{id:"starter",name:"Starter",tagline:"For active Indian-market users.",monthlyPriceInr:1200,launchPriceInr:1200,highlights:["Everything in Free","Indian market live workflow","90 automation actions/month","Up to 20 AI requests/day","More strategy templates","Backtesting and risk tools"],simpleExamples:["Build an Indian-market strategy with AI","Review risk before a trade","Deploy strategies with higher limits"],entitlements:{plan:"starter",markets:["india"],paperAccounts:3,strategyLimit:20,backtestRunsPerMonth:100,aiCreditsPerMonth:600,automationActionsPerMonth:90,liveExecutionsPerMonth:90,priority:"standard",concurrentStrategies:3}},
{id:"pro",name:"Pro",tagline:"Indian markets plus crypto when live.",monthlyPriceInr:3499,highlights:["Indian market access","Crypto included when Zerion launches it","500 automation actions/month","1,000 AI credits/month","AI strategy builder","Advanced backtesting"],simpleExamples:["Build and test a strategy","Analyze charts and compare setups","Run more automated scans"],entitlements:{plan:"pro",markets:["india","crypto"],paperAccounts:8,strategyLimit:100,backtestRunsPerMonth:500,aiCreditsPerMonth:1000,automationActionsPerMonth:500,liveExecutionsPerMonth:500,priority:"standard",concurrentStrategies:8,cryptoIncludedWhenLive:true}},
{id:"elite",name:"Elite",tagline:"Indian + Forex + crypto-ready access.",monthlyPriceInr:5499,featured:true,highlights:["Indian + Forex access","Crypto included when live","1,100 automation actions/month","2,500 AI credits/month","Priority AI queue","Advanced risk controls"],simpleExamples:["Compare India and Forex setups","Create a trade proposal with risk and quantity","Run larger strategy workflows"],entitlements:{plan:"elite",markets:["india","forex","crypto"],paperAccounts:20,strategyLimit:300,backtestRunsPerMonth:1500,aiCreditsPerMonth:2500,automationActionsPerMonth:1100,liveExecutionsPerMonth:1100,priority:"priority",concurrentStrategies:15,cryptoIncludedWhenLive:true}},
{id:"ultra",name:"Ultra",tagline:"High limits for serious Zerion users.",monthlyPriceInr:7499,highlights:["All supported markets","Up to 10x Starter automation capacity","5,000 AI credits/month","1,500 automation actions/month","Priority processing","More concurrent strategies"],simpleExamples:["Monitor many strategies","Use AI through research and review","Run higher-volume backtesting"],entitlements:{plan:"ultra",markets:["india","forex","crypto"],paperAccounts:30,strategyLimit:600,backtestRunsPerMonth:3500,aiCreditsPerMonth:5000,automationActionsPerMonth:1500,liveExecutionsPerMonth:1500,priority:"priority",concurrentStrategies:30,cryptoIncludedWhenLive:true}},
{id:"prime",name:"Prime",tagline:"Very high limits with fair-use protection.",monthlyPriceInr:12499,highlights:["All supported markets","15,000 AI credits/month","10,000 automation actions/month","Highest normal-user priority","Large strategy and backtest limits","Fair-use protection"],simpleExamples:["Use Zerion heavily across research and execution","Run large strategy portfolios","Use PowerX at the highest normal-user tier"],entitlements:{plan:"prime",markets:["india","forex","crypto"],paperAccounts:100,strategyLimit:2000,backtestRunsPerMonth:15000,aiCreditsPerMonth:15000,automationActionsPerMonth:10000,liveExecutionsPerMonth:10000,priority:"highest",concurrentStrategies:100,cryptoIncludedWhenLive:true}},
{id:"enterprise",name:"Enterprise",tagline:"Custom infrastructure, limits and support.",monthlyPriceInr:null,enterprise:true,highlights:["Custom market and usage limits","Team and organization controls","Custom AI/API integrations","Dedicated infrastructure options","Custom support and onboarding"],simpleExamples:["Deploy Zerion for a team","Request dedicated PowerX infrastructure","Integrate internal workflows"],entitlements:{plan:"enterprise",markets:["india","forex","crypto"],paperAccounts:1000,strategyLimit:10000,backtestRunsPerMonth:100000,aiCreditsPerMonth:100000,automationActionsPerMonth:100000,liveExecutionsPerMonth:null,priority:"custom",concurrentStrategies:1000,cryptoIncludedWhenLive:true}}
];
export const planEntitlements=Object.fromEntries(planDefinitions.map(p=>[p.id,p.entitlements])) as Record<Plan,Entitlements>;
export function getPlan(plan: Plan): PlanDefinition {
  const found = planDefinitions.find((item) => item.id === plan);

  if (!found) {
    throw new Error(`Unknown Zerion plan: ${plan}`);
  }

  return found;
}
