FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./

RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY app ./app

EXPOSE 10000

CMD ["sh","-c","python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-10000} --workers 1"]
