"use client";
import { useEffect,useState } from "react";
import { BellRing, Mail, Smartphone, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
type Preferences={in_app:boolean;email:boolean;push:boolean;trade_fills:boolean;risk_events:boolean;market_alerts:boolean};
const defaults:Preferences={in_app:true,email:true,push:false,trade_fills:true,risk_events:true,market_alerts:true};
export function NotificationPreferences(){const [value,setValue]=useState(defaults);const [state,setState]=useState("Loading…");useEffect(()=>{fetch("/api/account/preferences?kind=notifications").then(r=>r.json()).then(j=>{if(j.data?.payload)setValue({...defaults,...j.data.payload});setState("")}).catch(()=>setState("Unable to load"));},[]);async function save(){setState("Saving…");const r=await fetch("/api/account/preferences",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"notifications",payload:value})});setState(r.ok?"Saved securely":"Save failed")}
const rows:[[keyof Preferences,string,string,typeof BellRing],...Array<[keyof Preferences,string,string,typeof BellRing]>]=[["in_app","In-app notifications","Important updates inside Zerion X1",BellRing],["email","Email summaries","Security events, reports and account notices",Mail],["push","Push notifications","Mobile browser notifications when supported",Smartphone],["trade_fills","Paper order fills","Order fills, rejections and position changes",BellRing],["risk_events","Risk events","Kill-switch, drawdown and exposure warnings",ShieldAlert],["market_alerts","Market alerts","Price alerts and strategy-trigger notifications",BellRing]];
return <section className="x1-menu-group"><div className="x1-panel-heading"><div><span className="x1-kicker">Account-persisted</span><h3>Notification channels</h3></div><span className="text-sm text-white/50">{state}</span></div>{rows.map(([key,title,description,Icon])=><label className="x1-toggle-row" key={key}><span className="x1-menu-icon"><Icon/></span><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={value[key]} onChange={e=>setValue(v=>({...v,[key]:e.target.checked}))}/><i/></label>)}<div className="mt-5"><Button onClick={save}>Save notification settings</Button></div></section>}
