import "server-only";
import { adminInsert, adminRest, adminSelect } from "@/lib/supabase/admin-rest";
import { quoteStore } from "@/lib/market/quote-store";
type Row=Record<string,unknown>;const n=(v:unknown)=>(Number.isFinite(Number(v))?Number(v):0);
export type SignalValidationSummary={sampleSize:number;wins:number;losses:number;expired:number;winRate:number|null;calibrated:boolean;minimumSample:number;minimumObservedWinRate:number};
const MIN_SAMPLE=20,MIN_WIN_RATE=70;
export async function resolveOpenSignalOutcomes(){const rows=await adminSelect("signal_outcomes","outcome=eq.open&order=generated_at.asc&limit=300");for(const row of rows){const symbol=String(row.symbol??"");if(!symbol)continue;const quote=await quoteStore.get(symbol).catch(()=>null);if(!quote)continue;const side=String(row.side??"").toLowerCase(),price=n(quote.price),stop=n(row.stop_loss),target=n(row.target_price),expiresAt=Date.parse(String(row.expires_at??""));let outcome:"win"|"loss"|"expired"|null=null,rMultiple=0;if(side==="buy"){if(target&&price>=target){outcome="win";rMultiple=3}else if(stop&&price<=stop){outcome="loss";rMultiple=-1}}else if(side==="sell"){if(target&&price<=target){outcome="win";rMultiple=3}else if(stop&&price>=stop){outcome="loss";rMultiple=-1}}if(!outcome&&Number.isFinite(expiresAt)&&expiresAt<=Date.now()){outcome="expired";rMultiple=0}if(!outcome)continue;await adminRest(`signal_outcomes?id=eq.${encodeURIComponent(String(row.id))}`,{method:"PATCH",body:JSON.stringify({outcome,r_multiple:rMultiple,last_price:price,resolved_at:new Date().toISOString()})});if(row.opportunity_id)await adminRest(`agent_opportunities?id=eq.${encodeURIComponent(String(row.opportunity_id))}`,{method:"PATCH",body:JSON.stringify({status:"expired",updated_at:new Date().toISOString()})}).catch(()=>{})}}
export async function registerSignalOutcome(input:{opportunityId:string;symbol:string;side:"buy"|"sell";entry:number;stopLoss:number;target:number;confidence:number;qualityScore:number;generatedAt:string;expiresAt:string}){await adminInsert("signal_outcomes?on_conflict=opportunity_id",[{opportunity_id:input.opportunityId,symbol:input.symbol,side:input.side,entry_price:input.entry,stop_loss:input.stopLoss,target_price:input.target,confidence:input.confidence,quality_score:input.qualityScore,outcome:"open",generated_at:input.generatedAt,expires_at:input.expiresAt}],"resolution=merge-duplicates,return=representation")}
export async function getSignalValidationSummary():Promise<SignalValidationSummary>{const rows=await adminSelect("signal_outcomes","outcome=in.(win,loss,expired)&order=resolved_at.desc&limit=200"),wins=rows.filter(r=>r.outcome==="win").length,losses=rows.filter(r=>r.outcome==="loss").length,expired=rows.filter(r=>r.outcome==="expired").length,resolved=wins+losses;return{sampleSize:resolved,wins,losses,expired,winRate:resolved?Number(((wins/resolved)*100).toFixed(1)):null,calibrated:resolved>=MIN_SAMPLE,minimumSample:MIN_SAMPLE,minimumObservedWinRate:MIN_WIN_RATE}}
export function validationAllowsPublishing(s:SignalValidationSummary){if(!s.calibrated)return true;return(s.winRate??0)>=s.minimumObservedWinRate}
