"use client";
import { useEffect,useMemo,useState } from "react";
const lessons=[
 {id:"risk",title:"Risk before return",level:"Foundation",minutes:8,content:"Define risk per trade, maximum daily loss and invalidation before placing an order."},
 {id:"paper",title:"Paper-order lifecycle",level:"Practice",minutes:12,content:"Understand pending, filled, rejected and cancelled states before connecting a broker."},
 {id:"strategy",title:"Build a testable strategy",level:"Builder",minutes:15,content:"Combine a data source, indicator, condition, entry, exit and explicit risk rules."},
 {id:"backtest",title:"Read a backtest honestly",level:"Research",minutes:14,content:"Use out-of-sample data, costs and drawdown—not only win rate—to judge robustness."},
 {id:"probability",title:"Probability is not certainty",level:"AI Safety",minutes:10,content:"Treat confidence as calibrated evidence with invalidation and scenario ranges, never a guarantee."},
];
export function LearningCenter(){const [query,setQuery]=useState("");const [completed,setCompleted]=useState<string[]>([]); useEffect(()=>{try{setCompleted(JSON.parse(localStorage.getItem("zerion-learning")??"[]") as string[]);}catch{setCompleted([]);}},[]);const visible=useMemo(()=>lessons.filter(x=>`${x.title} ${x.level}`.toLowerCase().includes(query.toLowerCase())),[query]);function toggle(id:string){setCompleted(current=>{const next=current.includes(id)?current.filter(x=>x!==id):[...current,id];localStorage.setItem("zerion-learning",JSON.stringify(next));return next;});}return <><div className="panel"><label>Search lessons<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Risk, paper trading, backtesting…"/></label><p className="mt-3 text-sm text-white/55">Progress {completed.length}/{lessons.length}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2">{visible.map(lesson=><article key={lesson.id} className="panel"><div className="flex justify-between gap-4"><div><p className="eyebrow">{lesson.level} · {lesson.minutes} min</p><h2 className="mt-2 text-2xl font-semibold">{lesson.title}</h2></div><input type="checkbox" aria-label={`Complete ${lesson.title}`} checked={completed.includes(lesson.id)} onChange={()=>toggle(lesson.id)}/></div><p className="mt-4 text-white/65">{lesson.content}</p><a className="mt-5 inline-block text-sm text-amber-100" href={lesson.id==="paper"?"/dashboard/paper":lesson.id==="strategy"?"/dashboard/strategies":lesson.id==="backtest"?"/dashboard/backtests":"/dashboard/risk"}>Open related workspace →</a></article>)}</div></>;}
