"use client";
import { useMemo,useState } from "react";
import { Activity,Bitcoin,Landmark,RefreshCw,ShieldCheck,WalletCards } from "lucide-react";
type Broker="upstox"|"coindcx"|"exness-mt5";
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
export function LiveTradingCommandCenter(){const[broker,setBroker]=useState<Broker>("upstox"),[data,setData]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function sync(){setBusy(true);setError("");try{const r=await fetch(`/api/live/account?broker=${broker}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error?.message??"Sync failed");setData(j.data??{})}catch(e){setError(e instanceof Error?e.message:"Sync failed")}finally{setBusy(false)}}
const summary=useMemo(()=>{if(!data)return[];if(broker==="upstox"){const p=((data.positions as {data?:unknown[]}|undefined)?.data??[]).length,h=((data.holdings as {data?:unknown[]}|undefined)?.data??[]).length,o=((data.orders as {data?:unknown[]}|undefined)?.data??[]).length;return [["Open positions",p],["Holdings",h],["Orders today",o]]}if(broker==="coindcx"){const b=(data.balances as Array<{balance?:number;locked_balance?:number}>|undefined)??[];const f=b.filter(x=>num(x.balance)+num(x.locked_balance)>0);return [["Funded assets",f.length],["Balance rows",b.length]]}const a=(data.account??{}) as Record<string,unknown>,ps=(data.positions??{}) as Record<string,unknown>;const pc=Array.isArray(ps.positions)?ps.positions.length:0;return [["MT5 login",String(a.login??"—")],["Balance",num(a.balance).toLocaleString()],["Equity",num(a.equity).toLocaleString()],["Open positions",pc]]},[broker,data]);
const label=broker==="upstox"?"Upstox":broker==="coindcx"?"CoinDCX":"Exness MT5";
return <div className="space-y-6"><section className="zx-command-hero"><div><p className="eyebrow">Live trading command center</p><h1>Connected accounts in one clear live workspace.</h1><p>India, Crypto and Forex execution stay separated by provider and user authorization.</p></div><div className="zx-command-orb"><Activity/></div></section><div className="zx-switch-grid zx-live-broker-switch"><button className={broker==="upstox"?"is-active":""} onClick={()=>{setBroker("upstox");setData(null)}}><Landmark/><span>Indian Markets</span><small>Upstox</small></button><button className={broker==="coindcx"?"is-active":""} onClick={()=>{setBroker("coindcx");setData(null)}}><Bitcoin/><span>Crypto</span><small>CoinDCX</small></button><button className={broker==="exness-mt5"?"is-active":""} onClick={()=>{setBroker("exness-mt5");setData(null)}}><WalletCards/><span>Forex</span><small>Exness MT5</small></button></div><section className="zx-live-panel"><div className="zx-live-panel__head"><div><p className="eyebrow">{label}</p><h2>Live account state</h2></div><button className="zx-secondary-action" onClick={()=>void sync()} disabled={busy}><RefreshCw className="mr-2 h-4 w-4"/>{busy?"Syncing…":"Sync now"}</button></div>{error?<div className="zx-error-banner">{error}</div>:null}{!data?<div className="zx-empty-state"><ShieldCheck/><h3>Ready when you are</h3><p>Sync the linked account to load authorized live account information.</p></div>:<div className="zx-stat-grid">{summary.map(([l,v])=><article key={String(l)}><span>{l}</span><strong>{String(v)}</strong></article>)}</div>}</section></div>}
