"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
type Row=Record<string,unknown>;const n=(v:unknown)=>Number(v??0);const rows=(v:unknown)=>v&&typeof v==="object"&&Array.isArray((v as {data?:unknown}).data)?(v as {data:Row[]}).data:[];
export function LiveSectionWorkspace({mode}:{mode:"order"|"pnl"|"history"|"broker-account"}){
 const[data,setData]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const[token,setToken]=useState(""),[qty,setQty]=useState("1"),[side,setSide]=useState<"BUY"|"SELL">("BUY"),[type,setType]=useState<"MARKET"|"LIMIT"|"SL"|"SL-M">("MARKET"),[price,setPrice]=useState(""),[trigger,setTrigger]=useState(""),[proposal,setProposal]=useState<{action:string;fields:Record<string,string>}|null>(null);
 async function sync(){setBusy(true);setError("");try{const r=await fetch("/api/live/account?broker=upstox",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error?.message??"Broker sync failed");setData(b.data??{})}catch(e){setError(e instanceof Error?e.message:"Broker sync failed")}finally{setBusy(false)}}
 useEffect(()=>{if(mode!=="order")void sync()},[mode]);
 const positions=useMemo(()=>rows(data?.positions),[data]),orders=useMemo(()=>rows(data?.orders),[data]),trades=useMemo(()=>rows(data?.trades),[data]);
 const pnl=positions.reduce((s,r)=>s+n(r.pnl??r.unrealised??r.unrealized_pnl),0);
 async function createProposal(){setBusy(true);setError("");setProposal(null);try{const order={quantity:Number(qty),product:"I",validity:"DAY",instrument_token:token,order_type:type,transaction_type:side,is_amo:false,...(type==="LIMIT"||type==="SL"?{price:Number(price)}:{}),...(type==="SL"||type==="SL-M"?{trigger_price:Number(trigger)}:{})};const r=await fetch("/api/live/order-proposal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({broker:"upstox",order})}),b=await r.json();if(!r.ok)throw new Error(b.error?.message??"Proposal failed");setProposal({action:b.data.confirmation.action,fields:b.data.confirmation.fields})}catch(e){setError(e instanceof Error?e.message:"Proposal failed")}finally{setBusy(false)}}
 const head=(t:string,d:string)=><div className="page-heading"><div><p className="eyebrow">LIVE TRADING · UPSTOX</p><h1>{t}</h1><p>{d}</p></div></div>;
 if(mode==="order")return <main className="dashboard-page">{head("Live Order","Zerion creates a proposal; final live order remains behind explicit Upstox confirmation.")}<section className="panel max-w-3xl space-y-4"><label>Upstox instrument token<input value={token} onChange={e=>setToken(e.target.value)} placeholder="Select/copy a provider instrument token"/></label><div className="grid gap-3 sm:grid-cols-3"><label>Side<select value={side} onChange={e=>setSide(e.target.value as "BUY"|"SELL")}><option>BUY</option><option>SELL</option></select></label><label>Order type<select value={type} onChange={e=>setType(e.target.value as typeof type)}><option>MARKET</option><option>LIMIT</option><option>SL</option><option>SL-M</option></select></label><label>Qty<input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/></label></div>{type==="LIMIT"||type==="SL"?<label>Price<input type="number" value={price} onChange={e=>setPrice(e.target.value)}/></label>:null}{type==="SL"||type==="SL-M"?<label>Trigger<input type="number" value={trigger} onChange={e=>setTrigger(e.target.value)}/></label>:null}<button className="zx-primary-action" disabled={busy||!token||!Number(qty)} onClick={()=>void createProposal()}>{busy?"Creating proposal…":"Review live proposal"}</button>{error?<div className="zx-error-banner">{error}</div>:null}{proposal?<form action={proposal.action} method="POST"><p className="mb-3 text-sm">Proposal created. Continue only if you want to open the Upstox confirmation step.</p>{Object.entries(proposal.fields).map(([k,v])=><input key={k} type="hidden" name={k} value={v}/>) }<button className="zx-exit-action" type="submit">Continue to Upstox confirmation</button></form>:null}</section></main>;
 if(mode==="pnl")return <main className="dashboard-page">{head("Live P&L","Calculated only from current broker position data.")}<div className="panel"><span>Current broker P&L</span><strong className={`mt-2 block text-3xl ${pnl>=0?"positive":"negative"}`}>{pnl.toLocaleString()}</strong><p className="mt-2 text-xs text-white/45">{positions.length} broker position rows</p></div>{error?<div className="zx-error-banner mt-4">{error}</div>:null}</main>;
 if(mode==="history")return <main className="dashboard-page">{head("Live History","Orders and trades returned by the connected Upstox account.")}<section className="panel"><h2 className="text-lg font-semibold">Orders</h2>{orders.map((r,i)=><div className="border-b border-white/10 py-3" key={String(r.order_id??i)}>{String(r.trading_symbol??r.tradingsymbol??r.instrument_token??"Order")} · {String(r.status??"")}</div>)}</section><section className="panel mt-4"><h2 className="text-lg font-semibold">Trades</h2>{trades.map((r,i)=><div className="flex justify-between border-b border-white/10 py-3" key={String(r.trade_id??i)}><Link href={`/dashboard/charts?symbol=${encodeURIComponent(String(r.trading_symbol??r.tradingsymbol??""))}&tf=5m`}>{String(r.trading_symbol??r.tradingsymbol??r.instrument_token??"Trade")} · Open chart</Link><span>{String(r.quantity??"")}</span></div>)}</section></main>;
 const profile=(data?.profile as {data?:Row}|undefined)?.data??{},funds=(data?.funds as {data?:unknown}|undefined)?.data;
 return <main className="dashboard-page">{head("Broker Account","Connected broker identity, funds and sync state.")}<section className="panel space-y-3"><button className="zx-secondary-action" disabled={busy} onClick={()=>void sync()}>{busy?"Syncing…":"Refresh broker"}</button>{error?<div className="zx-error-banner">{error}</div>:null}{data?<><div><span>User</span><strong className="ml-2">{String(profile.user_name??profile.user_id??"Connected")}</strong></div><div><span>Email</span><strong className="ml-2">{String(profile.email??"—")}</strong></div><pre className="max-h-72 overflow-auto rounded-xl bg-black/20 p-3 text-xs">{JSON.stringify(funds??{},null,2)}</pre></>:<p>Broker state not loaded.</p>}</section></main>;
}
